swagger: "2.0"
info:
  title: Sport Shoe
  description: This is a website of sport
  version: 1.0.0
  contact:
    name: TTCN Team
    email: thantoandoc83@gmail.com
  termsOfService: apiteam@gmail.com
  license:
    name: Nodejs
    url: https://nodejs.org
host: localhost:3008
basePath: /api
schemes:
  - http
tags:
  - name: users
    description: Everything about users
  - name: auth
    description: Authentication
  - name: shoes
    description: "Every shoes in shop"
paths:
  /users:
    get:
      tags:
        - users
      summary: Get all users in database
      description: ""
      consumes:
        - "appication/json"
      produces: 
        - "appication/json"
      responses:
        200:
          description: "List users"
          schema :
            type: array
            items: 
              $ref: "#/definitions/Users"
        400:
          description: "Invalid status value"
    post:
      tags:
        - users
      summary: "Register new account"
      produces: 
        - "appication/json"
      consumes:
        - "appication/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            properties: 
              lastName : 
                type : "string"
              firstName : 
                type : "string"
              email : 
                type : "string"
                uniqueItems: true
              password: 
                type : "string"
      responses:
        201:
          description: "Success"
        404:
          description: "Failure"
      deprecated: false
  /login:
    post:
      tags:
        - auth
      consumes :
        - "application/json"
      produces : 
        - "application/json"
      summary: "Login into shop"
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties: 
              email :
                type : "string"
              password : 
                type : "string"
      responses:
        200:
          description: "Login success"
          schema:
            properties: 
              token:
                type : "string"
              user:
                $ref: "#/definitions/Users"
        
      deprecated: false
  /shoes:
    get:
      tags:
        - shoes
      responses:
        500:
          description: "Internal Error"

definitions:
  Users :
    type : object
    properties: 
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
        uniqueItems: true
      phone:
        type: "string"
      avatar:
        type: "string"
      role:
        type : "string"
        enum:
          - "user"
          - "admin"
    xml:
      name: Users